<form id="loginForm" action="/auth/login" method="post">
    <div id="sysLogin">
        <div id="login_container" class="container">
            <h2 class="green_tag_short">Login</h2>
           
            <?php if (isset($this->error)) { 
                      echo "<div id='login_message' class='message error'>";
                      echo $this->escape(' ', 'none');
                      echo $this->escape($this->error);  
                      echo "</div>";
                  }
            ?>
           
            <div id="login_form_block" class="form_block"> 
                <ol>
                    <li>
                        <label id="label_username" for="username">Username</label>
                        <input class="textfield required" id="username" maxlength="200"
                               name="username" type="text" value="" tabindex="1"/>
                        <script type="text/javascript">
                            document.getElementById("username").focus();
                    </script>
                    </li>
                    <li>
                        <label id="label_password" for="userpass">Password</label>
                        <input class="textfield required" id="userpass" maxlength="30"
                               name="userpass" type="password" value="" tabindex="2"/>
                    </li>
                    <li class="submit_block">
                        <input type="button" name="login" id="login" tabindex="3"/>
                        <span id="forgot_password">
                            <a href="/auth/forgot_password">Forgot your password?</a>&nbsp;
                                <strong>&bull;</strong>&nbsp;
                            <a href="/incident/report">Report Incident</a>
                        </span>
                    </li>
                </ol>
            </div>
        </div>
    </div>  
    
    <!-- System Usage ROB -->
    <div id="sysUsage" style="display:none;">
        <div id="login_container" class="container">
            <h2 class="yellow_tag_short">Warning</h2>
            <div id="login_form_block" class="form_block"> 
                <div style="padding: 0 10px 5px; font-size: 100%;">
                    <?php echo $this->escape(Fisma::configuration()->getConfig('use_notification'), 'none');?>
                </div>
                <hr />
                <div class="submit_block">
                    <h3 style="text-align: center; margin-bottom: 0; margin-top: 0; padding-bottom: 15px;
                        padding-top: 10px; font-weight: bold;">&nbsp;
                        <input type="button" id="accept" value="Accept" class="primary button" tabindex="4" />&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" id="cancel" value="Cancel" class="primary button" tabindex="5" />
                    </h3>
                </div>
            </div>
        </div>
    </div>
</form>                