
INSERT INTO `configurations` VALUES 
(1,'max_absent_time','90','Absent days of an account causing being disabled');

INSERT INTO `evaluations` (`id`, `name`, `precedence_id`, `function_id`, `group`) VALUES 
(1, 'EV_SSO', 0, 0, 'EVIDENCE'),
(2, 'EV_FSA', 1, 0, 'EVIDENCE'),
(3, 'EV_IVV', 2, 0, 'EVIDENCE'),
(4, 'EST', 0, 0, 'ACTION'),
(5, 'SSO', 4, 0, 'ACTION');

/* default user roles setup in openfisma */
INSERT INTO `roles` VALUES 
(3,'Information System Security Officer','ISSO','[NIST Special Publication 800-37 Definition] The information system security officer is the individual responsible to the authorizing official, information system owner, or the senior agency information security officer for ensuring the appropriate operational security posture is maintained for an information system or program. The information system security officer also serves as the principal advisor to the authorizing official, information system owner, or senior agency information security officer on all matters (technical and otherwise) involving the security of the information system. The information system security officer typically has the detailed knowledge and expertise required to manage the security aspects of the information system and, in many agencies, is assigned responsibility for the day-to-day security operations of the system. This responsibility may also include, but is not limited to, physical security, personnel security, incident handling, and security training and awareness. The information system security officer may be called upon to assist in the development of the system security policy and to ensure compliance with that policy on a routine basis. In close coordination with the information system owner, the information system security officer often plays an active role in developing and updating the system security plan as well as in managing and controlling changes to the system and assessing the security impact of those changes. [OpenFISMA definition] The Information Systems Security Officer Group is designed to allow Information System Security Officers the ability to identify, assess, prioritize, and monitor the progress of corrective efforts for security weaknesses found in thier system.'),
(5,'Reviewer','REVIEWER','[OpenFISMA Definition] The Reviewer Group gives users the ability to view all information on the Plan of Actions and Milestones report for the information system. They do not have the ability to create, edit, or delete any information.'),
(6,'System Operational Staff','SOP','This group represents the userbase who will be fixing the identified security weaknesses. They have rights to create mitigation strategies, upload evidence, and view and generate reports on open and closed findings. An example would be a System Admin responsible for patching the Windows Servers, or Database Admin in charge of a particular database.'),
(7,'Independent Verification and Validation','IV&V','The Independent Verification and Validation group serves as a third party independent of the correction process who validates whether or not the security weakness has been successfully closed. They have the ability to view all agency Plan of Actions and Milestone information and the ability to close an open item.'),
(8,'Senior Agency Information Security Officer','SAISO','[NIST 800-37 Definition] The senior agency information security officer is the agency official responsible for: (i) carrying out the Chief Information Officer responsibilities under FISMA; (ii) possessing professional qualifications, including training and experience, required to administer the information security program functions; (iii) having information security duties as that official’s primary duty; and (iv) heading an office with the mission and resources to assist in ensuring agency compliance with FISMA. The senior agency information security officer (or supporting staff member) may also serve as the authorizing officials designated representative. The senior agency information security officer serves as the Chief Information Officer’s primary liaison to the agency’s authorizing officials, information system owners, and information system security officers. [OpenFISMA Definition] The SAISO has the ability to view all agency wide Plan of Actions and Milestone information as well as generate reports and provide comments and guidance to the Information System Security Officers through the remediation page.'),
(10,'Application Administrator','ADMIN','[OpenFISMA Definition] The Application Administrators group provides administrative privileges to the OpenFISMA application. Users will have the ability to access all security controls and functions.'),
(11,'Certification Agent','AUDITOR','[NIST 800-37 Definition] The certification agent is an individual, group, or organization responsible for conducting a security certification, or comprehensive assessment of the management, operational, and technical security controls in an information system to determine the extent to which the controls are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the security requirements for the system. The certification agent also provides recommended corrective actions to reduce or eliminate vulnerabilities in the information system. Prior to initiating the security assessment activities that are a part of the certification process, the certification agent provides an independent assessment of the system security plan to ensure the plan provides a set of security controls for the information system that is adequate to meet all applicable security requirements. [OpenFISMA Definition] This group is used by independent auditors to view finding information, create findings, set initial risk levels, and provide recommended corrective actions.'),
(13,'Information System Owner','ISO','[NIST 800-37 Definition] The information system owner is an agency official responsible for the overall procurement, development, integration, modification, or operation and maintenance of an information system. The information system owner is responsible for the development and maintenance of the system security plan and ensures the system is deployed and operated according to the agreed-upon security requirements. The information system owner is also responsible for deciding who has access to the information system (and with what types of privileges or access rights) and ensures that system users and support personnel receive the requisite security training (e.g., instruction in rules of behavior). The information system owner informs key agency officials of the need to conduct a security certification and accreditation of the information system, ensures that appropriate resources are available for the effort, and provides the necessary system-related documentation to the certification agent. The information system owner receives the security assessment results from the certification agent. After taking appropriate steps to reduce or eliminate vulnerabilities, the information system owner assembles the security accreditation package and submits the package to the authorizing official or the authorizing official’s designated representative for adjudication. The role of information system owner can be interpreted in a variety of ways depending on the particular agency and the system development life cycle phase of the information system. Some agencies may refer to information system owners as program managers or business/asset/mission owners. In some situations, the notification of the need to conduct a security certification and accreditation may come from the senior agency information security officer or authorizing official as they endeavor to ensure compliance with federal or agency policy. The responsibility for ensuring appropriate resources are allocated to the security certification and accreditation effort depends on whether the agency uses a centralized or decentralized funding mechanism. Depending on how the agency has organized and structured its security certification and accreditation activities, the authorizing official may choose to designate an individual other than the information system owner to compile and assemble the information for the accreditation package. In this situation, the designated individual must coordinate the compilation and assembly activities with the information system owner.');

