<div class="approvalHeader">
    <b>File: </b>

    <a href='/finding/remediation/downloadevidence/id/<?php echo $this->escape($this->artifact->id)?>' target='_blank'>
        <?php echo $this->escape($this->artifact->filename); ?>
    </a>

    submitted by 

    <?php 
        $user = $this->artifact->User;
        $fullName = isset($user) ? $user->nameFirst . ' ' . $user->nameLast : '';
        $username = isset($user) ? $user->username : '';
        
        echo $this->escape($this->userInfo($fullName, $username), 'none');
    ?> 
    on 
    <?php echo $this->escape($this->artifact->createdTs); ?>
</div>
