<?php
    $finding = $this->finding;
?>
<div id='finding_detail_panel'><?php
echo $this->partial(
    'remediation/finding-detail.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'isLegacyFindingKeyEditable' => $this->isLegacyFindingKeyEditable,
        'isSourceEditable' => $this->isSourceEditable,
        'isOrganizationEditable' => $this->isOrganizationEditable,
        'isPocEditable' => $this->isPocEditable
    )
);
?></div>

<?php
if ($this->isDescriptionEditable) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if ($this->isRecommendationEditable) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->recommendation, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
echo $this->partial(
    'remediation/poam-table.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'isMitigationStrategyEditable' => $this->isMitigationStrategyEditable,
        'isTypeEditable' => $this->isTypeEditable
    )
);
?>

<?php
echo $this->partial(
    'remediation/poam-approval.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'approvalHistory' => $this->approvalHistory
    )
);
?>