<?php
    $finding = $this->finding;
    $status  = $finding->getStatus();
?>
<div id='finding_detail_panel'><?php
echo $this->partial(
    'remediation/finding-detail.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'isLegacyFindingKeyEditable' => $this->isLegacyFindingKeyEditable,
        'isSourceEditable' => $this->isSourceEditable,
        'isOrganizationEditable' => $this->isOrganizationEditable,
        'isPocEditable' => $this->isPocEditable,
        'approvalHistory' => $this->approvalHistory
    )
);
?></div>

<div style='width:66%'>
<?php
    Fisma_Format_Section::startSection("Details");
?>
<table class="keyValues" style='width:100%'>
<?php if (Fisma::configuration()->getConfig('use_legacy_finding_key')): ?>
    <tr>
        <td>Legacy Finding Key:</td>
        <td colspan='3'>
            <span
                <?php
                if ($this->isLegacyFindingKeyEditable) {
                ?>
                    id="legacyFindingKey"
                    class="editable"
                    target="legacyFindingKey"
                    name="finding[legacyFindingKey]"
                    type="text"
                <?php
                }
                ?>>
                <?php echo $this->escape($finding->legacyFindingKey); ?>&nbsp;
            </span>
        </td>
    </tr>
<?php endif; ?>
    <tr>
        <td>Status:</td>
        <td title="<?php echo $this->escape($status); ?>" colspan='3'>
            <?php echo $this->escape($finding->getLongStatus()); ?>
        </td>
    </tr>
    <tr>
        <td>Source:</td>
        <td>
            <span id="source"
                  type="select"
                  name="finding[sourceId]"
                  href="/metainfo/list/o/source/format/html/"
                  value="<?php echo $this->escape($finding->Source->id); ?>">
                  <?php
                  $sourceName = $finding->Source->nickname;
                  if ($this->acl()->hasPrivilegeForObject('read', $finding->Source)):
                  ?>
                      <a href="/finding/source/view/id/<?php echo $this->escape($finding->Source->id); ?>">
                         <?php echo $this->escape($sourceName);?>
                      </a>
                  <?php
                  else:
                      echo $this->escape($sourceName);
                  endif;
                  ?>
            </span>

            <?php
            if ($this->isSourceEditable):
            ?>
                <span class="editable" target="source">&nbsp;</span>
            <?php
            endif;
            ?>

        <?php if ($finding->uploadId): ?>
            <br/><?php echo $this->escape($finding->Upload->fileName
                . ', uploaded on ' . $finding->Upload->createdTs .'.'); ?>
        <?php endif; ?>
        </td>
        <td>
            <div>
                Assignment:
            </div>
        </td>
        <td>
            <span id="organization"
                  type="select"
                  name="finding[responsibleOrganizationId]"
                  href="/metainfo/list/o/system/format/html/"
                  value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
            <a href="<?php echo $this->escape($this->organizationViewUrl); ?>">
                 <?php echo $this->escape($finding->Organization->nickname);?>
            </a>
            </span>

            <?php
            if ($this->isOrganizationEditable):
            ?>
                <span class="editable" target="organization">&nbsp;</span>
            <?php
            endif;
            ?>
        </td>
    </tr>
    <tr>
    <?php if ($status != 'CLOSED'): ?>
        <td>On Time:</td>
        <td>
            <span class='<?php
                switch($this->onTimeState) {
                    case 'On Time':
                        echo 'LOW';
                        break;
                    case 'N/A':
                        echo 'MEDIUM';
                        break;
                    case 'Overdue':
                        echo 'HIGH';
                        break;
                }
            ?>'><?php echo $this->escape($this->onTimeState); ?></span>
    </td>
    <?php endif; ?>
    <?php if (Fisma::configuration()->getConfig('threat_type') == 'threat_level'): ?>
        <td>Threat Level:</td>
        <td><span class='<?php echo $this->escape($finding->threatLevel); ?>'>
            <?php echo $this->escape($finding->threatLevel); ?>
        </span></td>
    <?php endif; ?>
    <?php if (Fisma::configuration()->getConfig('threat_type') == 'residual_risk'): ?>
        <td>Residual Risk:</td>
        <td><span class='<?php echo $this->escape($finding->residualRisk); ?>'>
            <?php echo $this->escape($finding->residualRisk); ?>
        </span></td>
    <?php endif; ?>
    </tr>
    <tr>
        <td>Plan of Action:</td>

        <td><span type="select" name="finding[type]" href="/metainfo/list/o/type/format/html/" id="type"
            <?php
                if ($this->isTypeEditable) {
                    echo $this->escape('class="editable" target="type"', 'none');
                }
            ?>>
            <?php echo $this->escape($finding->type)?>
        </span></td>
        <td>Security Control</td>
        <td><?php echo $this->finding->SecurityControl ?></td>
    </tr>
</table>
<?php Fisma_Format_Section::stopSection();

if ($this->isDescriptionEditable) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if ($this->isRecommendationEditable) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->recommendation, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
echo $this->partial(
    'remediation/poam-table.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'isMitigationStrategyEditable' => $this->isMitigationStrategyEditable,
        'isTypeEditable' => $this->isTypeEditable
    )
);
?>
</div>
