<?php
    $finding = $this->finding;
    $orgId = $finding->Organization->nickname;
    $status  = $finding->getStatus();
?>
<div id='finding_detail_panel'>
        <?php Fisma_Format_Section::startSection("Details"); ?>
        <table class="keyValues">
            <tr>
                <td>Legacy Finding Key:</td>
                <td>
                    <span
                        <?php
                        if ($this->isLegacyFindingKeyEditable) {
                        ?>
                            id="legacyFindingKey"
                            class="editable"
                            target="legacyFindingKey"
                            name="finding[legacyFindingKey]"
                            type="text"
                        <?php
                        }
                        ?>>
                        <?php echo $this->escape($finding->legacyFindingKey); ?>&nbsp;
                    </span>
                </td>
            </tr>
            <tr>
                <td>Source:</td>
                <td>
                    <span id="source"
                          type="select"
                          name="finding[sourceId]"
                          href="/metainfo/list/o/source/format/html/"
                          value="<?php echo $this->escape($finding->Source->id); ?>">
                          <?php
                          $sourceName = $finding->Source->nickname . ' - ' . $finding->Source->name;
                          if ($this->acl()->hasPrivilegeForObject('read', $finding->Source)):
                          ?>
                              <a href="/finding/source/view/id/<?php echo $this->escape($finding->Source->id); ?>">
                                 <?php echo $this->escape($sourceName);?>
                              </a>
                          <?php
                          else:
                              echo $this->escape($sourceName);
                          endif;
                          ?>
                    </span>

                    <?php
                    if ($this->isSourceEditable):
                    ?>
                        <span class="editable" target="source">&nbsp;</span>
                    <?php
                    endif;
                    ?>

                <?php if ($finding->uploadId): ?>
                    <br><?php echo $this->escape($finding->Upload->fileName)?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        Organization/System:
                    </div>
                </td>
                <td>
                    <span id="organization"
                          type="select"
                          name="finding[responsibleOrganizationId]"
                          href="/metainfo/list/o/system/format/html/"
                          value="<?php echo $this->escape($finding->responsibleOrganizationId); ?>">
                    <a href="<?php echo $this->escape($this->organizationViewUrl); ?>">
                         <?php echo $this->escape($finding->Organization->nickname);?>
                         - <?php echo $this->escape($finding->Organization->name);?>
                    </a>
                    </span>

                    <?php
                    if ($this->isOrganizationEditable):
                    ?>
                        <span class="editable" target="organization">&nbsp;</span>
                    <?php
                    endif;
                    ?>
                </td>
            </tr>
            <tr>
                <td>Status:</td>
                <td title="<?php echo $this->escape($status); ?>">
                    <?php echo $this->escape($finding->getLongStatus()); ?>
                </td>
            </tr>
            <?php if ($status != 'CLOSED'): ?><tr>
                <td>On Time:</td>
                <td>
                <?php if (is_null($finding->nextDueDate)): ?>
                    N/A
                <?php elseif (time() <= strtotime($finding->nextDueDate)): ?>
                    On Time
                <?php else: ?>
                    Overdue
                <?php endif; ?>
                </td>
            </tr><?php endif; ?>
        </table>
        <?php Fisma_Format_Section::stopSection(); ?>

        <?php Fisma_Format_Section::startSection("Dates"); ?>
        <table class="keyValues">
            <tr>
                <td>Date Discovered:</td>
                <td><?php echo $this->escape($finding->discoveredDate)?></td>
            </tr>
            <tr>
                <td>Date Opened:</td>
                <td><?php echo $this->escape($finding->createdTs)?></td>
            </tr>

            <?php if (!$finding->ecdLocked): ?>
            <tr>
                <td>Expected Completion Date:</td>
                <td>
                <span name="finding[currentEcd]" id="currentEcd" type="text"
                    <?php
                        if ($finding->isEcdEditable()) {
                            echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                        }
                        echo $this->escape('>', 'none');
                        echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd), 'none');
                    ?>
                </span>
                </td>
            </tr>
            <?php else: ?>
            <!--
                    The original ECD indicates the estimated completion date that was agreed upon when the finding
                    was first approved, and it cannot be changed.
                    The current ECD can be changed, but you must provide a written justification for the change.
            -->

            <tr>
                <td>Original ECD:</td>
                <td><?php echo $this->escape($finding->originalEcd); ?></td>
            </tr>

            <tr>
                <div><!-- Rendering calendar depends on this div -->
                    <td>Current ECD:</td>
                    <td><span name="finding[currentEcd]" id="currentEcd" type="text"
                        <?php
                            if ($finding->isEcdEditable()) {
                                echo $this->escape(' class="date editable" target="currentEcd"', 'none');
                                $onclick = "Fisma.Finding.editEcdJustification();";
                                echo $this->escape('onclick="', 'none');
                                echo $this->escape($onclick, 'none');
                                echo $this->escape('"', 'none');
                            }
                            echo $this->escape('>', 'none');
                            echo $this->escape((empty($finding->currentEcd) ? 'NONE' : $finding->currentEcd));
                        ?>
                    </span></td>
                </div>
            </tr>

            <tr>
                <td>Justification for changing the ECD: </td>
                <td id="currentChangeDescription"><?php echo $this->escape($finding->ecdChangeDescription); ?></td>
            </tr>
            <?php endif; ?>

            <tr>
                <td>Date Completed: </td>
                <td>
                    <?php
                        if (empty($finding->actualCompletionDate)) {
                            echo $this->escape('(not completed)', 'none');
                        } else {
                            echo $this->escape($finding->actualCompletionDate, 'none');
                        }
                    ?>
                </td>
            </tr>

            <tr>
                <td>Date Closed:</td>
                <td>
                    <?php
                    if (!is_null($finding->closedTs)) {
                        echo $this->escape($finding->closedTs);
                    } else {
                        echo $this->escape("Not closed");
                    }
                    ?>
                </td>
            </tr>
        </table>
        <?php Fisma_Format_Section::stopSection(); ?>

        <?php Fisma_Format_Section::startSection("People"); ?>
        <table class="keyValues">
            <tr>
                <td>Opened By:</td>
                <td><?php echo $this->escape($this->userInfo($finding->CreatedBy->username), 'none'); ?></td>
            </tr>
            <tr>
                <td>Point Of Contact:</td>
                <td>
                <span id="pointOfContact"
                      type="autocomplete"
                      xhr="/poc/autocomplete/format/json"
                      queryPrepend="/keyword/"
                      schemaObject="pointsOfContact"
                      schemaField="name"
                      name="finding[pocId]"
                      <?php
                      if ($this->acl()->hasPrivilegeForClass('create', 'Poc')):
                      ?>
                          setupCallback="Fisma.Finding.setupPocAutocomplete"
                      <?php
                      endif;
                      ?>
                      value="<?php echo $this->escape($finding->pocId); ?>"
                      defaultValue="<?php echo $this->escape($finding->PointOfContact->username); ?>">

                     <?php echo $this->escape($this->userInfo($finding->PointOfContact->username), 'none');?>
                </span>

                <?php
                if ($this->isPocEditable):
                ?>
                    <span class="editable" target="pointOfContact">&nbsp;</span>
                <?php
                endif;
                ?>
            </tr>
        </table>
        <?php Fisma_Format_Section::stopSection(); ?>
</div>

<?php
if ($this->isDescriptionEditable) {
    Fisma_Format_Section::startSection('Description', 'finding_description');
} else {
    Fisma_Format_Section::startSection('Description');
}
?>
<div name="finding[description]" id="finding_description" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->description, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
if ($this->isRecommendationEditable) {
    Fisma_Format_Section::startSection('Recommendation', 'recommendation');
} else {
    Fisma_Format_Section::startSection('Recommendation');
}
?>
<div name="finding[recommendation]" id="recommendation" type="textarea" rows="3" cols="160">
    <?php echo $this->escape($finding->recommendation, 'none'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>

<?php
echo $this->partial(
    'remediation/poam-table.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'isMitigationStrategyEditable' => $this->isMitigationStrategyEditable,
        'isTypeEditable' => $this->isTypeEditable
    )
);
?>

<?php
echo $this->partial(
    'remediation/poam-approval.partial.phtml',
    'finding',
    array(
        'finding' => $finding,
        'approvalHistory' => $this->approvalHistory
    )
);
?>