<?php
Fisma_Format_Section::startSection("Approvals for Plan of Actions & Milestones");
$finding = $this->finding;

// Evaluate the completion of the POA&Ms
$poam_completion = array(
    'Plan of Action'                => $finding->type,
    'Finding Description'           => $finding->description,
    'Finding Recommendation'        => $finding->recommendation,
    'Estimated Completion Date'     => $finding->currentEcd,
    'Security Control'              => $finding->securityControlId,
    'Threat Level'                  => $finding->threatLevel,
    'Threat Description'            => $finding->threat,
    'Countermeasure Effectiveness'  => $finding->countermeasuresEffectiveness,
    'Countermeasure Description'    => $finding->countermeasures
);
$complete = true;
foreach ($poam_completion as $key => $row) {
    $row = strip_tags($row);
    if (in_array($row, array('', 'NONE', '0000-00-00', 'N/A'))) {
        $complete = false;
    } else {
        unset($poam_completion[$key]);
    }
}

// Prepare POA&Ms submission controls
$warning = "WARNING: You are about to submit mitigation strategy. This action cannot be undone. "
           . 'Please click "YES" to confirm your action or click "No" to stop.';
$args = array(null, '/finding/remediation/msa/do/submitmitigation/id/', $finding->id);

// Submit button
if ('NEW' == $finding->status || 'DRAFT' == $finding->status) {
    $submitMitigationButton = new Fisma_Yui_Form_Button(
        'submitMitigation',
        array(
              'label' => 'Submit Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' => $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $warning
              )
        )
    );

    if (
        $finding->isDeleted() ||
        false == $complete ||
        !$this->acl()->hasPrivilegeForObject('mitigation_strategy_submit', $finding)
    ) {
        $submitMitigationButton->readOnly = true;
    }
?>
    <p><i>In order to submit the POA&amp;Ms for approval, you must have selected a plan of action, created one or more milestones, and completed the risk analysis.</i></p>

    <?php if (count($poam_completion) > 0): ?>
        <p>Remaining to be done:</p>
        <ul id='poam_remaining'>
            <?php foreach ($poam_completion as $key => $row): ?>
                <li>Fill in <?php echo $this->escape($key); ?> section.</li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <div class='buttonBar'><?php echo $this->escape($submitMitigationButton, 'none')?></div>
<?php
}

// Revise button
if (
    !$finding->isDeleted() &&
    'EN' == $finding->status &&
    $this->acl()->hasPrivilegeForObject('mitigation_strategy_revise', $finding)
) {
    $message = 'The revised mitigation strategy must be fully approved before evidence can be re-submitted.'
             . ' Are you sure that you want to continue?';
    $args = array(null, '/finding/remediation/msa/do/revisemitigation/id/', $finding->id);
    $reviseMitigationButton = new Fisma_Yui_Form_Button(
        'reviseMitigationButton',
        array(
              'label' => 'Revise Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' =>  $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $message
            )
        )
    );
?>
    <div class='buttonBar'><?php echo $this->escape($reviseMitigationButton, 'none')?></div>
<?php
}

// Prepare approval controls
if ($finding->status == 'MSA') {
    echo $this->escape("<div class='approvalHeader'><b>Approval</b></div><div class='approval'>", 'none');
    $activeEvaluation = $finding->CurrentEvaluation;
    if ($activeEvaluation->id != null && $activeEvaluation->approvalGroup == 'action') {
        echo $this->escape('<div class="approvalStep"><b>', 'none');
        echo $this->escape($activeEvaluation->name);
        echo $this->escape('</b>', 'none');
        if (
            !$finding->isDeleted() &&
            $this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $finding)
        ) {
            echo $this->escape('<input type="hidden" name="comment" value="" />', 'none');
            echo $this->escape('<input type="hidden" name="decision" value="APPROVED" />', 'none');

            $approveButton = new Fisma_Yui_Form_Button(
                'approveButton',
                array(
                    'label' => 'APPROVE',
                    'onClickFunction' => 'Fisma.Remediation.remediationAction',
                    'onClickArgument' => array(
                        'action' => "APPROVED",
                        'formId' => "finding_detail",
                        'panelTitle' => "Mitigation Strategy Approval",
                        'findingId' => $finding->id
                    )
                )
            );
            echo $this->escape($approveButton, 'none');

            $denyButton = new Fisma_Yui_Form_Button(
                'denyButton',
                array(
                    'label' => 'DENIED',
                    'onClickFunction' => 'Fisma.Remediation.remediationAction',
                    'onClickArgument' => array(
                        'action' => "DENIED",
                        'formId' => "finding_detail",
                        'panelTitle' => "Mitigation Strategy Denial",
                        'findingId' => $finding->id
                    )
                )
            );

            echo $this->escape($denyButton, 'none');
        } else {
            echo $this->escape("PENDING", 'none');
        }
        echo $this->escape('</div>', 'none');
    }

    $disableEvaluations = array();
    $currentEvaluation  = $finding->CurrentEvaluation;
    if ($currentEvaluation->approvalGroup == 'action') {
        while ($currentEvaluation->nextId != null) {
            $currentEvaluation    = $currentEvaluation->NextEvaluation;
            $disableEvaluations[] = $currentEvaluation;
        }
    }

    foreach ($disableEvaluations as $evaluation) {
        echo $this->escape('<div class="approvalStep"><b>', 'none');
        echo $this->escape($evaluation->name);
        echo $this->escape('</b>N/A</div>', 'none');
    }
    echo $this->escape('</div>', 'none');
}

// Print the history table (if not empty)
if (!empty($this->approvalHistory)):
?>
<div class='approvalHeader'><b>History</b></div>
<div class='approval'>
<?php
$decidedTypes = array(); // Hightlight only the latest decision of each approval type
foreach ($this->approvalHistory as $findingEvaluation):
    $highlighted = '';
    if (!in_array($findingEvaluation->Evaluation->id, $decidedTypes)):
        $decidedTypes[] = $findingEvaluation->Evaluation->id;
        $highlighted = ' highlight';
    endif;

    $user = $findingEvaluation->User;
    $userHtml = $this->userInfo($user->nameFirst . ' ' . $user->nameLast, $user->username);
    $decision = $findingEvaluation->decision;
    $spanClass = strtolower($decision);
    $comment = (!empty($findingEvaluation->comment)) ?
               $this->textToHtml($this->escape($findingEvaluation->comment)) :
               "";
?>
    <div class='approvalStep<?php echo $this->escape($highlighted); ?>'>
        <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?></b>
        <span class='<?php echo $this->escape($spanClass); ?>'>
            <b><?php echo $this->escape($decision); ?></b>
            by <?php echo $this->escape($userHtml, 'none'); ?>
            at <?php echo $this->escape($findingEvaluation->createdTs); ?>
        </span>
        <?php echo $this->escape($comment, 'none'); ?>
    </div>
<?php
endforeach;
?>
</div> <!-- end of div.approval -->
<?php
endif;

Fisma_Format_Section::stopSection();
?>
