<?php
Fisma_Format_Section::startSection("Approvals for Plan of Actions & Milestones");
$finding = $this->finding;

// Evaluate the completion of the POA&Ms
$poam_completion = array(
    'Plan of Action'                => $finding->type,
    'Finding Description'           => $finding->description,
    'Finding Recommendation'        => $finding->recommendation,
    'Expected Completion Date'     => $finding->currentEcd,
    'Security Control'              => $finding->securityControlId,
    'Threat Level'                  => $finding->threatLevel,
    'Threat Description'            => $finding->threat,
    'Countermeasure Effectiveness'  => $finding->countermeasuresEffectiveness,
    'Countermeasure Description'    => $finding->countermeasures
);
$complete = true;
foreach ($poam_completion as $key => $row) {
    $row = strip_tags($row);
    if (in_array($row, array('', 'NONE', '0000-00-00', 'N/A'))) {
        $complete = false;
    } else {
        unset($poam_completion[$key]);
    }
}

// Prepare POA&Ms submission controls
$warning = "WARNING: You are about to submit mitigation strategy. This action cannot be undone. "
           . 'Please click "YES" to confirm your action or click "No" to stop.';
$args = array(null, '/finding/remediation/msa/do/submitmitigation/id/', $finding->id);

// Submit button
if ('NEW' == $finding->status || 'DRAFT' == $finding->status) {
    $submitMitigationButton = new Fisma_Yui_Form_Button(
        'submitMitigation',
        array(
              'label' => 'Submit Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' => $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $warning
              )
        )
    );

    if (
        $finding->isDeleted() ||
        false == $complete ||
        !$this->acl()->hasPrivilegeForObject('mitigation_strategy_submit', $finding)
    ) {
        $submitMitigationButton->readOnly = true;
    }
?>
    <?php if (count($poam_completion) > 0): ?>
        <p><i>In order to submit the POA&amp;Ms for approval, you must have selected a plan of action, created one or more milestones, and completed the risk analysis.</i></p>

        <p>Remaining to be done:</p>
        <ul id='poam_remaining'>
            <?php foreach ($poam_completion as $key => $row): ?>
                <li>Fill in <?php echo $this->escape($key); ?> section.</li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <div class='buttonBar'><?php echo $this->escape($submitMitigationButton, 'none')?></div>
<?php
}

// Revise button
if (
    !$finding->isDeleted() &&
    'EN' == $finding->status &&
    $this->acl()->hasPrivilegeForObject('mitigation_strategy_revise', $finding)
) {
    $message = 'The revised mitigation strategy must be fully approved before evidence can be re-submitted.'
             . ' Are you sure that you want to continue?';
    $args = array(null, '/finding/remediation/msa/do/revisemitigation/id/', $finding->id);
    $reviseMitigationButton = new Fisma_Yui_Form_Button(
        'reviseMitigationButton',
        array(
              'label' => 'Revise Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' =>  $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $message
            )
        )
    );
?>
    <div class='buttonBar'><?php echo $this->escape($reviseMitigationButton, 'none')?></div>
<?php
}

// Prepare approval controls
?>
<?php if ($finding->status == 'MSA') {
    $activeEvaluation = $finding->CurrentEvaluation;
    if (
        !$finding->isDeleted() &&
         $this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $finding)
    ) {
?>
        <div class='buttonBar'>
            <input type="hidden" name="comment" value="" />
            <input type="hidden" name="decision" value="APPROVED" />
<?php
        $approveButton = new Fisma_Yui_Form_Button(
            'approveButton',
            array(
                'label' => 'APPROVE',
                'onClickFunction' => 'Fisma.Remediation.remediationAction',
                'onClickArgument' => array(
                    'action' => "APPROVED",
                    'formId' => "finding_detail",
                    'panelTitle' => "Mitigation Strategy Approval",
                    'findingId' => $finding->id
                )
            )
        );
        echo $this->escape($approveButton, 'none');

        $denyButton = new Fisma_Yui_Form_Button(
            'denyButton',
            array(
                'label' => 'DENY',
                'onClickFunction' => 'Fisma.Remediation.remediationAction',
                'onClickArgument' => array(
                    'action' => "DENIED",
                    'formId' => "finding_detail",
                    'panelTitle' => "Mitigation Strategy Denial",
                    'findingId' => $finding->id
                )
            )
        );

        echo $this->escape($denyButton, 'none');
?>
        </div>
<?php
    } else {
?>
        <div class='findingStatus'>
            <b>Status: </b>
            <span><?php echo $this->escape($this->finding->getLongStatus()); ?></span>
        </div>
<?php
    }
}
?>
<?php

// Print the history table (if not empty)
if (!empty($this->approvalHistory)):
?>
<div class='approvalHeader'><b>History</b> <a href='#' onclick='jQuery("b.aview").toggle();return false;'>[Switch view]</a></div>
<div class='approval'>
<?php
foreach ($this->approvalHistory as $findingEvaluation):
    $user = $findingEvaluation->User;
    $userHtml = $this->userInfo($user->nameFirst . ' ' . $user->nameLast, $user->username);
    $decision = $findingEvaluation->decision;
    $spanClass = strtolower($decision);
    $comment = (!empty($findingEvaluation->comment)) ?
               $this->textToHtml($this->escape($findingEvaluation->comment)) :
               "";
?>
    <div class='approvalStep'>
        <b class='aview'><?php echo $this->escape($findingEvaluation->Evaluation->name); ?><br/><br/></b>
        <span class='<?php echo $this->escape($spanClass); ?>'>
            <b><?php echo $this->escape($decision); ?></b>
            by <?php echo $this->escape($userHtml, 'none'); ?>
            at <?php echo $this->escape($findingEvaluation->createdTs); ?>
        </span>
        <?php echo $this->escape($comment, 'none'); ?>
    </div>
<?php
endforeach;
?>
</div> <!-- end of div.approval -->
<script>
jQuery('b.aview').hide();
</script>
<?php
endif;

Fisma_Format_Section::stopSection();
?>
