<?php
Fisma_Format_Section::startSection("Approvals for Plan of Actions & Milestones");
$finding = $this->finding;

$array = array('type'                   => $finding->type,
               'description'            => $finding->description,
               'recommendation'         => $finding->recommendation,
               'resources'              => $finding->resourcesRequired,
               'ECD'                    => $finding->currentEcd,
               'blscr'                  => $finding->securityControlId,
               'threat_level'           => $finding->threatLevel,
               'threat_source'          => $finding->threat,
               'cmeasure_effectiveness' => $finding->countermeasuresEffectiveness,
               'cmeasure'               => $finding->countermeasures);
$complete = true;
foreach ($array as $row) {
    $row = strip_tags($row);
    if ($row == '' || $row == 'NONE' || $row == '0000-00-00') {
        $complete = false;
        continue;
    }
}

$warning = "WARNING: You are about to submit mitigation strategy. This action cannot be undone. "
           . 'Please click "YES" to confirm your action or click "No" to stop.';
$args = array(null, '/finding/remediation/msa/do/submitmitigation/id/', $finding->id);

if ('NEW' == $finding->status || 'DRAFT' == $finding->status) {
    $submitMitigationButton = new Fisma_Yui_Form_Button(
        'submitMitigation',
        array(
              'label' => 'Submit Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' => $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $warning
              )
        )
    );

    if (
        $finding->isDeleted() ||
        false == $complete ||
        !$this->acl()->hasPrivilegeForObject('mitigation_strategy_submit', $finding)
    ) {
        $submitMitigationButton->readOnly = true;
    }
?>
    <p><i>The mitigation strategy, security control, and risk analysis sections must
          be fully completed before this can be submitted for approval.</i></p>

    <div class='buttonBar'><?php echo $this->escape($submitMitigationButton, 'none')?></div>
<?php
}

if (
    !$finding->isDeleted() &&
    'EN' == $finding->status &&
    $this->acl()->hasPrivilegeForObject('mitigation_strategy_revise', $finding)
) {
    $message = 'The revised mitigation strategy must be fully approved before evidence can be re-submitted.'
             . ' Are you sure that you want to continue?';
    $args = array(null, '/finding/remediation/msa/do/revisemitigation/id/', $finding->id);
    $reviseMitigationButton = new Fisma_Yui_Form_Button(
        'reviseMitigationButton',
        array(
              'label' => 'Revise Mitigation Strategy',
              'onClickFunction' => 'Fisma.Util.showConfirmDialog',
              'onClickArgument' => array(
                  'args' =>  $args,
                  'func' => 'Fisma.Util.formPostAction',
                  'text' => $message
            )
        )
    );
?>
    <div class='buttonBar'><?php echo $this->escape($reviseMitigationButton, 'none')?></div>
<?php
}

if ($finding->status == 'MSA') {
    echo $this->escape("<div class='approvalHeader'><b>Approval History</b></div><div class='approval'>", 'none');
    $activeEvaluation = $finding->CurrentEvaluation;
    if ($activeEvaluation->id != null && $activeEvaluation->approvalGroup == 'action') {
        echo $this->escape('<div class="approvalStep"><b>', 'none');
        echo $this->escape($activeEvaluation->name);
        echo $this->escape('</b>', 'none');
        if (
            !$finding->isDeleted() &&
            $this->acl()->hasPrivilegeForObject($activeEvaluation->Privilege->action, $finding)
        ) {
            echo $this->escape('<input type="hidden" name="comment" value="" />', 'none');
            echo $this->escape('<input type="hidden" name="decision" value="APPROVED" />', 'none');

            $approveButton = new Fisma_Yui_Form_Button(
                'approveButton',
                array(
                    'label' => 'APPROVE',
                    'onClickFunction' => 'Fisma.Remediation.remediationAction',
                    'onClickArgument' => array(
                        'action' => "APPROVED",
                        'formId' => "finding_detail",
                        'panelTitle' => "Mitigation Strategy Approval",
                        'findingId' => $finding->id
                    )
                )
            );
            echo $this->escape($approveButton, 'none');

            $denyButton = new Fisma_Yui_Form_Button(
                'denyButton',
                array(
                    'label' => 'DENIED',
                    'onClickFunction' => 'Fisma.Remediation.remediationAction',
                    'onClickArgument' => array(
                        'action' => "DENIED",
                        'formId' => "finding_detail",
                        'panelTitle' => "Mitigation Strategy Denial",
                        'findingId' => $finding->id
                    )
                )
            );

            echo $this->escape($denyButton, 'none');
        } else {
            echo $this->escape("PENDING", 'none');
        }
        echo $this->escape('</div>', 'none');
    }

    $disableEvaluations = array();
    $currentEvaluation  = $finding->CurrentEvaluation;
    if ($currentEvaluation->approvalGroup == 'action') {
        while ($currentEvaluation->nextId != null) {
            $currentEvaluation    = $currentEvaluation->NextEvaluation;
            $disableEvaluations[] = $currentEvaluation;
        }
    }

    foreach ($disableEvaluations as $evaluation) {
        echo $this->escape('<div class="approvalStep"><b>', 'none');
        echo $this->escape($evaluation->name);
        echo $this->escape('</b>N/A</div>', 'none');
    }
    echo $this->escape('</div>', 'none');
}

// Print the history table (if not empty)
if (!empty($this->approvalHistory)):
?>
<div class='approvalHeader'><b>Approval History</b></div>
<div class='approval'>
<?php
$decidedTypes = array(); // Hightlight only the latest decision of each approval type
foreach ($this->approvalHistory as $findingEvaluation):
    $highlighted = '';
    if (!in_array($findingEvaluation->Evaluation->id, $decidedTypes)):
        $decidedTypes[] = $findingEvaluation->Evaluation->id;
        $highlighted = ' highlight';
    endif;

    $user = $findingEvaluation->User;
    $userHtml = $this->userInfo($user->nameFirst . ' ' . $user->nameLast, $user->username);
    $decision = $findingEvaluation->decision;
    $spanClass = strtolower($decision);
    $comment = (!empty($findingEvaluation->comment)) ?
               $this->textToHtml($this->escape($findingEvaluation->comment)) :
               "";
?>
    <div class='approvalStep<?php echo $this->escape($highlighted); ?>'>
        <b><?php echo $this->escape($findingEvaluation->Evaluation->name); ?></b>
        <span class='<?php echo $this->escape($spanClass); ?>'>
            <b><?php echo $this->escape($decision); ?></b>
            by <?php echo $this->escape($userHtml, 'none'); ?>
            at <?php echo $this->escape($findingEvaluation->createdTs); ?>
        </span>
        <?php echo $this->escape($comment, 'none'); ?>
    </div>
<?php
endforeach;
?>
</div> <!-- end of div.approval -->
<?php
endif;

Fisma_Format_Section::stopSection();
?>