<?php Fisma_Format_Section::startSection('Email validation message&hellip;'); ?>
<b><?php echo $this->msg; ?></b>
<p>
    Technical Support Contact: <?php echo $this->contactName;?><br>
    Contact Phone: <?php echo $this->contactPhone;?><br>
    Contact E-mail: <a href="mailto:<?php echo $this->contactEmail;?>">
            <?php echo $this->contactEmail;?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
