<div>
    <i>
        System policy states that you must review and accept the Rules of Behavior
        for <?php echo $this->systemName;?> every
        <?php echo $this->robDuration;?> days. If you do not accept these
        rules then you will be logged off.
    </i>
</div>

<?php Fisma_Format_Section::startSection($this->systemName . ' Rules of Behavior'); ?>
<div>
    <?php echo $this->behaviorRule; ?>
</div>

<div>
    <?php
    echo new Fisma_Yui_Form_Button_Link('cancel', 
                                  array('value' => 'Cancel', 
                                        'href' => '/auth/logout'));
    echo new Fisma_Yui_Form_Button_Link('accept', 
                                  array('value' => 'Accept', 
                                        'href' => '/user/accept-rob'));
    ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
