<div id="<?php echo  $this->escape($this->tabViewContainer, 'none') ?>">
    <ul>
    <?php foreach ($this->tabs as $tab): ?>
        <li>
            <a href="<?php echo $this->escape($tab['url']) ?>">
                <span><?php echo  $this->escape($tab['name'], 'none') ?></span>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
    <!-- YUI will load the tabview into this div -->
</div>

<script type="text/javascript">
    $(function(){
        $( "#<?php echo  $this->escape($this->tabViewContainer, 'none') ?>" ).tabs({
            cache: true,
            cookie: { expires: 365 },
            spinner: "Loading... <img height='12' src='/images/spinners/small.gif'>",
            fx: { opacity: 'toggle', duration: 'fast' },
            load: Fisma.Editable.setupEditFields
        });
    });
</script>
