<?php 
Fisma_Format_Section::startSection("Workflow Steps"); 

if ('closed' == $this->incident['status']):
?>
    <p>
        <b>
            This workflow has been completed and the incident is now officially closed.
        </b>
    </p>
<?php
endif;

foreach ($this->steps as $step):
    switch ($step['iw_status']):
        case 'current':
            $class = 'currentIncidentStep';
            break;
        case 'completed':
            $class = 'completedIncidentStep';
            break;
        case 'queued':
            $class = 'queuedIncidentStep';
            break;
    endswitch;
?>
    <form method="post" action="/incident/complete-workflow-step/id/<?php echo $this->id; ?>">
        <input type="hidden" name="stepId" value="">
        <div class="incidentStep <?php echo $class; ?>">
            <div class="incidentCardinality">
                <?php echo ($step['iw_cardinality'] + 1); ?>
            </div>
            <table>
                <tr>
                    <td>Step:</td>
                    <td><?php echo $step['iw_name']; ?></td>
                </tr>
                <tr>
                    <td>Status:</td>
                    <td><?php echo ucfirst($step['iw_status']); ?></td>
                </tr>
                <?php
                if (!is_null($step['iw_userId'])):
                ?>
                    <tr>
                        <td>Completion Date:</td>
                        <td>
                            <?php echo empty($step['iw_completeTs']) ? 'n/a' : $step['iw_completeTs']; ?>
                        </td>
                    </tr>
                <?php
                endif;

                if (!is_null($step['iw_userId'])):
                ?>
                    <tr>
                        <td>Completed By:</td>
                        <td><?php 
                            if ($this->readUserObjPrivilege) {
                                echo "<a href='/panel/user/sub/view/id/{$step['iw_userId']}'>" 
                                   . "{$step['u_nameFirst']} {$step['u_nameLast']} ({$step['u_username']})</a>";
                            }
                            ?>
                        </td>
                    </tr>
                <?php
                endif;

                if (!is_null($step['iw_roleId'])):
                ?>
                    <tr>
                        <td>Role Required:</td>
                        <td><?php echo "({$step['r_nickname']}) {$step['r_name']}"; ?></td>
                    </tr>
                <?php
                endif;

                if (!empty($step['iw_description'])):
                ?>
                    <tr>
                        <td>Description:</td>
                        <td><?php echo $step['iw_description']; ?></td>
                    </tr>
                <?php
                endif;

                if (!empty($step['iw_comments'])):
                ?>
                    <tr>
                        <td>Comments:</td>
                        <td><?php echo Fisma_String::textToHtml($step['iw_comments']); ?></td>
                    </tr>
                <?php
                endif;

                if ('current' == $step['iw_status'] && $this->updateIncidentObjPrivilege):
                ?>
                    <tr>
                        <td>*Comments:</td>
                        <td>
                            <textarea rows="8" cols="60" name="comment"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <?php
                            echo new Fisma_Yui_Form_Button_Submit(
                                'completeStep', 
                                array('label' => 'Complete Step')
                            );
                            ?>
                        </td>
                    </tr>
                <?php
                endif;
                ?>            
            </table>
        </div>
    </form>
<?php 
endforeach;

Fisma_Format_Section::stopSection(); 
?>
