<?php
$operation = '';
if ($this->updateIrWorkflowDefPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteIrWorkflowDefPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Workflow Information</b> $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
