<?php
echo $this->partial('product/searchbox.phtml', array('createProductPrivilege' => $this->createProductPrivilege));

$operation = '';
if ($this->updateProductObjPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteProductObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Product Information $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
