Plugin:
    listeners: [XssListener, CacheListener]

    columns:
        name: 
            type: string(255)
            extra:
                purify: plaintext
        class:
            type: string(255)
            extra:
                purify: plaintext
        description: 
            type: string
            extra:
                purify: html
