Product:
    listeners: [IndexListener, NotificationListener]
    
    columns:
        vendor:
            type: string(255)
            extra:
                searchIndex: unstored
                notify: true
            comment: The name of the vendor who brands this product
        name:
            type: string(255)
            extra:
                searchIndex: unstored
                notify: true
            comment: Name of the product
        version:
            type: string(255)
            extra:
                searchIndex: keyword
                notify: true
            comment: Version of the product
        cpeName:
            type: string(255)
            unique: true
            extra:
                logicalName: CPE ID
                notify: true
            comment: The common platform enumeration (CPE) for this product, if known
