<?php
echo $this->partial('role/searchbox.phtml', array('createRolePrivilege' => $this->createRolePrivilege));
$operation = '';

if ($this->assignPrivilegesRoleObjPrivilege) {
    $operation .= "[<a href='{$this->rightLink}'>Right</a>]";
}

if ($this->updateRoleObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->editLink}'>Edit</a>]";
}

if ($this->deleteRoleObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}

Fisma_Format_Section::startSection("Role Information $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
