<?php
$operation = '';
if ($this->updateIrCategoryPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteIrCategoryPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Sub Category Information</b> $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
