<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="refresh" 
              content="<?php echo Configuration::getConfig('session_inactivity_period'); ?>;url=/auth/logout">

    <?php 
    $this->headTitle()->prepend(Configuration::getConfig('system_name'));
    echo $this->headTitle();

    $yuiComponents = array( 0 => 'yahoo', 1 => 'dom', 2 => 'event', 3 => 'element',
                            4 => 'container', 5 => 'json', 6 => 'cookie', 
                            7 => 'get', 8 => 'dragdrop', 9 => 'animation',
                            10 => 'menu', 11 => 'button', 12 => 'json', 
                            13 => 'connection', 'logger', 14 =>'tabview', 
                            15 => 'calendar', 16 => 'paginator', 17 => 'datasource',
                            18 => 'datatable', 19 => 'selector', 20 => 'treeview', 
                            21 => 'uploader', 22 => 'reset-fonts-grids'
                           );

    $components = array(
        "fismaJS" => array(
            "name" => 'fismaJS',
            "type" => 'js',
            "fullpath" => '/javascripts/fisma.js',
            "global" => true,
            "requires" => $yuiComponents
        ),
        "treetableJS" => array(
            "name" => 'treetableJS',
            "type" => 'js',
            "fullpath" => '/javascripts/TreeTable.js',
            "global" => true,
            "requires" => array (0 => 'fisma')
        ),
        "checkboxtreeJS" => array(
            "name" => 'checkboxtreeJS',
            "type" => 'js',
            "fullpath" => '/javascripts/CheckboxTree.js',
            "global" => true,
            "requires" => array (0 => 'treetable' )
        ),
        "editableJS" => array(
            "name" => 'editableJS',
            "type" => 'js',
            "fullpath" => '/javascripts/editable.js',
            "global" => true,
            "requires" => array (0 => 'checkboxtree')
        ),
        "helpJS" => array(
            "name" => 'helpJS',
            "type" => 'js',
            "fullpath" => '/javascripts/help.js',
            "global" => true,
            "requires" => array (0 => 'editable')
        ),
        "selectallselectnoneJS" => array(
            "name" => 'selectallselectnoneJS',
            "type" => 'js',
            "fullpath" => '/javascripts/selectallselectnone.js',
            "global" => true,
            "requires" => array (0 => 'help')
        ),
        "deleteconfirmJS" => array(
            "name" => 'deleteconfirmJS',
            "type" => 'js',
            "fullpath" => '/javascripts/deleteconfirm.js',
            "global" => true,
            "requires" => array (0 => 'selectallselectnone')
        ),
        "mainCSS" => array(
            "name" => 'mainCSS',
            "type" => 'css',
            "fullpath" => '/stylesheets/main.css',
            "global" => true
        ),
        "treetableCSS" => array(
            "name" => 'treetableCSS',
            "type" => 'css',
            "fullpath" => '/stylesheets/TreeTable.css',
            "global" => true
        )
    );


    $loader = new Fisma_Loader($components);
    $loader->load(array_keys($components));
    echo $loader;
    // @todo move below scripts into Fisma_Loader
    ?>


    <script type="text/javascript" src="/javascripts/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript" src="/javascripts/tiny_mce_config.js"></script>

    <?php 
    // @todo move into Fisma_Loader
    echo $this->headLink()->appendStylesheet('/yui/assets/skins/sam/skin.css', 'screen,print')
                          ->appendStylesheet('/stylesheets/print.css', 'print')
                          ->appendStylesheet('/stylesheets/ie7hacks.css', 'screen', 'IE 7')
                          ->appendStylesheet('/stylesheets/ie6hacks.css', 'screen', 'IE 6')
                          ->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
    ?>
    </head>
    <body class="yui-skin-sam">
        <div id='header' >
                <?php echo $this->layout()->header; ?>
        </div>

        <div class="externalMediaMarking">
            WARNING: This document is for internal, official use only.  This document contains sensitive computer 
            security related information. Public disclosure of this information would risk circumvention of the 
            law. Recipients of this document must not, under any circumstances, show or release its contents for 
            purposes other than official action. This document must be safeguarded to prevent improper disclosure. 
            Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.
        </div>
    
        <a name="contentStart"></a>
        <div id='content'>
                <?php echo $this->layout()->content; ?>
        </div>
        
        <div id='footer'>
                <?php echo $this->layout()->footer; ?>
        </div>
    </body>
</html>
