<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="refresh" 
              content="<?php echo Configuration::getConfig('session_inactivity_period'); ?>;url=/auth/logout">

    <?php 
    $this->headTitle()->prepend(Configuration::getConfig('system_name'));
    echo $this->headTitle();

    // Initialize and load the YUI components needed
    $yuiComponents = array('yahoo', 'dom', 'event', 'element', 'container', 'json', 'cookie', 'get', 'dragdrop', 
                           'animation', 'menu', 'button', 'json', 'connection', 'logger', 'tabview', 'calendar',
                           'paginator','datasource', 'datatable', 'selector', 'treeview', 'uploader','reset-fonts-grids');

    $yui = new Fisma_Loader();
    $yui->load($yuiComponents);
    echo $yui;

    $this->injectAsset('/javascripts/combined.js', 'js', true);
    echo $this->headScript()->appendFile('/javascripts/tiny_mce/tiny_mce.js');
    $this->injectAsset('/javascripts/tiny_mce_config.js', 'js');
    $this->injectAsset('/stylesheets/combined.css', 'css', true);
    $this->injectAsset('/stylesheets/print.css', 'css', false, 'print');
    $this->injectAsset('/stylesheets/ie7hacks.css', 'css', false, 'screen', 'IE 7');
    $this->injectAsset('/stylesheets/ie6hacks.css', 'css', false, 'screen', 'IE 6');

    echo $this->headLink()->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
    ?>
    </head>
    <body class="yui-skin-sam">
        <div id='header' >
                <?php echo $this->layout()->header; ?>
        </div>

        <div class="externalMediaMarking">
            WARNING: This document is for internal, official use only.  This document contains sensitive computer 
            security related information. Public disclosure of this information would risk circumvention of the 
            law. Recipients of this document must not, under any circumstances, show or release its contents for 
            purposes other than official action. This document must be safeguarded to prevent improper disclosure. 
            Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.
        </div>
    
        <a name="contentStart"></a>
        <div id='content'>
                <?php echo $this->layout()->content; ?>
        </div>
        
        <div id='footer'>
                <?php echo $this->layout()->footer; ?>
        </div>
    </body>
    <?php echo $this->partial('priorityMessage.phtml', array('messages' => $this->priorityMessenger())); ?>
</html>
