<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="refresh" 
              content="<?php echo Configuration::getConfig('session_inactivity_period'); ?>;url=/auth/logout">

    <?php 
    $this->headTitle()->prepend(Configuration::getConfig('system_name'));
    echo $this->headTitle();

    // Check for debug status, and set the JS/CSS postfix appropriately
    if(Fisma::debug())
    {
        $postfix = "";
    }
    else
    {
        $postfix = "-min." . Fisma::version();
    }

    // Initialize and load the YUI components needed
    $yuiComponents = array('yahoo','dom','event','element',
                            'container','json','cookie', 
                            'get','dragdrop','animation',
                            'menu','button','json', 
                            'connection','logger','tabview', 
                            'calendar','paginator','datasource',
                            'datatable','selector','treeview', 
                            'uploader','reset-fonts-grids'
                           );

    $yui = new Fisma_Loader();
    $yui->load($yuiComponents);
    echo $yui;

    // If we're in debug mode, we need to load the JS and CSS files individually
    if(Fisma::debug())
    {
        echo $this->headScript()->appendFile('/javascripts/fisma.js')
                                ->appendFile('/javascripts/TreeTable.js')
                                ->appendFile('/javascripts/CheckboxTree.js')
                                ->appendFile('/javascripts/editable.js')
                                ->appendFile('/javascripts/help.js')
                                ->appendFile('/javascripts/selectallselectnone.js')
                                ->appendFile('/javascripts/deleteconfirm.js');

        echo $this->headLink()->appendStylesheet('/stylesheets/main.css')
                              ->appendStylesheet('/stylesheets/TreeTable.css');
    }
    // Otherwise, load the combined and minified versions of these files 
    else
    {
        echo $this->headScript()->appendFile("/javascripts/combined$postfix.js");
        echo $this->headLink()->appendStylesheet("/stylesheets/combined$postfix.css");
    }

    echo $this->headScript()->appendFile("/javascripts/tiny_mce/tiny_mce.js")
                            ->appendFile("/javascripts/tiny_mce_config$postfix.js");

    echo $this->headLink()->appendStylesheet("/stylesheets/print$postfix.css", 'print')
                          ->appendStylesheet("/stylesheets/ie7hacks$postfix.css", 'screen', 'IE 7')
                          ->appendStylesheet("/stylesheets/ie6hacks$postfix.css", 'screen', 'IE 6')
                          ->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
    ?>
    </head>
    <body class="yui-skin-sam">
        <div id='header' >
                <?php echo $this->layout()->header; ?>
        </div>

        <div class="externalMediaMarking">
            WARNING: This document is for internal, official use only.  This document contains sensitive computer 
            security related information. Public disclosure of this information would risk circumvention of the 
            law. Recipients of this document must not, under any circumstances, show or release its contents for 
            purposes other than official action. This document must be safeguarded to prevent improper disclosure. 
            Staff reviewing this document must hold a minimum of Public Trust Level 5C clearance.
        </div>
    
        <a name="contentStart"></a>
        <div id='content'>
                <?php echo $this->layout()->content; ?>
        </div>
        
        <div id='footer'>
                <?php echo $this->layout()->footer; ?>
        </div>
    </body>
</html>
