<?php
    echo $this->escape("{$this->doctype()}\n", 'none');
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 

        <?php
        $this->headTitle()->prepend(Fisma::configuration()->getConfig('system_name'));
        echo $this->escape($this->headTitle(), 'none');
        $yuiComponents = array('yahoo', 'dom', 'event', 'element', 'container', 'button');

        $yui = new Fisma_Loader();
        $yui->load($yuiComponents);

        $this->headScript()->appendFile('/javascripts/jquery-min.js');
        $this->headScript()->appendFile('/javascripts/jquery-scrollTo-1-4-2-min.js');
        $this->headScript()->appendFile('/javascripts/jquery-localscroll-1-2-7-min.js');
        $this->headScript()->appendFile('/javascripts/jquery-serialScroll-1-2-2-min.js');
        $this->headScript()->appendFile('/javascripts/swfobject.js');
        $this->headScript()->appendFile('/javascripts/php.js');
        $this->headScript()->appendFile('/javascripts/Fisma.js');
        $this->injectAsset('/stylesheets/login.css', 'css', false, 'screen,print');
        $this->headLink()->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
        
        echo $this->escape($yui, 'none');
        echo $this->escape($this->headScript(), 'none');
        echo $this->escape($this->headLink(), 'none');
        ?>

        <script type="text/javascript">
            function capLock(e) {
                kc = e.keyCode ? e.keyCode : e.which;
                sk = e.shiftKey ? e.shiftKey : ((kc == 16) ? true : false);
                
                if(((kc >= 65 && kc <= 90) && !sk)||((kc >= 97 && kc <= 122) && sk)) {
                    document.getElementById('divCapsLock').className = 'divCapsLockON divCapsLock';
                }
                else {
                    document.getElementById('divCapsLock').className = 'divCapsLockOFF divCapsLock';
                }
            }

            $(function(){
                $('#login').click(function(){
                    var name = $("#username").val();
                    var pwd = $("#userpass").val();

                    if ((!name || 0 === name.length) && (!pwd || 0 === pwd.length)) {
                        alert("Please enter username and password");
                    }
                    else if (!name || 0 === name.length) {
                        alert("Please enter username");
                    }
                    else if (!pwd || 0 === pwd.length) {
                        alert("Please enter password");
                    }
                    else {
                        $('#sysUsage').toggle();
                        $('#sysLogin').toggle();
                    }
                });
                $('#accept').click(function(){
                    document.getElementById("loginForm").submit();
                });
                $('#cancel').click(function(){
                    $('#sysUsage').toggle();
                    $('#sysLogin').toggle();
                });
            });
    
        </script>
</head>

<body class="narrow_layout">

  <div id="master_container" class="container">
    <div id="wrapper" class="container">
      <div id="content" class="container">
        <div class="orange_container container overbottom">
          <div class="inner container">
            <div id="header" class="container">
              <div id="glow"></div>
            </div>
            <div class="content"></div>
          </div>
        </div>
        &nbsp;<br/>&nbsp;<br/>&nbsp;<br/>
        <div class="gray_container gradient container">
          <div class="content">
            <div class="white_content full_width">
              <div class="top"></div>
                <div class="middle">
                
                <!-- Login Form -->
                <?php echo $this->escape($this->layout()->content, 'none'); ?>

                </div>
                <div class="bottom"></div>
              </div>
            </div>
            <div id="footer">
              <div id="copyright_navigation">&copy; OpenFISMA 2012
                <span style="white-space: nowrap; ">
                  <a href="http://openfisma.org">Home</a>
                  <strong>&bull;</strong> <a href="/auth/rob">Rules of Behavior</a>
                  <strong>&bull;</strong> <a href="/auth/privacy">Privacy Policy</a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</body><?php echo $this->partial('partial/priorityMessage.phtml', array('messages' => $this->priorityMessenger())); ?>
</html>
