<?php echo "{$this->doctype()}\n" ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <?php
            echo $this->headTitle()->prepend(Configuration::getConfig('system_name'));

            // Check for debug status, and set the JS/CSS postfix appropriately
            if(Fisma::debug()) {
                $postfix = "";
            }
            else {
                $postfix = "-min." . Fisma::version();
            }

            // Initialize and load the YUI components needed for this page
            $yuiComponents = array( 'yahoo', 'dom', 'event', 'element',
                                    'button');

            $yui = new Fisma_Loader();
            $yui->load($yuiComponents);
            echo $yui;

            echo $this->headLink()->appendStylesheet("/stylesheets/main$postfix.css", 'screen,print')
                                  ->headLink(array('rel' => 'icon', 'href' => '/images/favicon.ico'));
        ?>
    </head>
    <body class="yui-skin-sam">
        <div id='container'>
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
