# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "computers", :force => true do |t|
    t.column "monitor",   :string
    t.column "cpu",       :string
    t.column "processor", :string
    t.column "stuff",     :string
    t.column "binary",    :binary
    t.column "boolean",   :boolean
    t.column "date",      :date
    t.column "datetime",  :datetime
    t.column "decimal",   :integer,  :limit => 10, :precision => 10, :scale => 0
    t.column "float",     :float
    t.column "integer",   :integer
    t.column "time",      :time
    t.column "timestamp", :datetime
  end

  create_table "rights", :force => true do |t|
    t.column "name",       :string
    t.column "controller", :string
    t.column "action",     :string
  end

  create_table "rights_roles", :id => false, :force => true do |t|
    t.column "right_id", :integer
    t.column "role_id",  :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "email",         :string
    t.column "password_hash", :string
    t.column "password_salt", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "number_mobile", :integer
    t.column "number_work",   :integer
    t.column "name_first",    :string
    t.column "name_last",     :string
  end

end
