<?php

/**
 * Task
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Task extends BaseTask
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMutator('status', 'setStatus');
    }
    /**
     * Mutator for status
     *
     * @param string $value Task status value
     * @return void
     */
    public function setStatus($status)
    {
        // Business rules for status changes
        switch ($status) {
            case 'running':
                $this->startedTs = Fisma::now();
                break;
            case 'finished':
                $this->finishedTs = Fisma::now();
                break;
        }
    }
}