<div id='toolbar' class="searchBox ui-widget-header ui-corner-all">
    <div class="left" id='toolbarLeft'>
        <button id='buttonBack'>Back</button>
        <?php
        foreach ($this->toolbarButtons as $button):
            echo $this->escape($button, 'none');
        endforeach;
        ?>
    </div>

    <div class="right" id='toolbarRight'>
        <?php if(isset($this->searchButtons)):
            foreach ($this->searchButtons as $button):
                echo $this->escape($button, 'none');
            endforeach;
        endif; ?>
    </div>

    <?php if(isset($this->searchForm)): ?>
        <div
            id='toolbarForm'
            class="<?php echo $this->escape(($this->searchFormLeft) ? 'left' : 'right'); ?>" style='margin-left:5px;'
        >
            <?php echo $this->escape($this->searchForm, 'none'); ?>
        </div>
    <?php endif; ?>

    <div class="clear"></div>
</div>
<script>
$(function(){
    $('#buttonBack')
        .button({icons: {primary:'ui-icon-arrowreturnthick-1-w'}})
        .click(Fisma.Util.goBack);
});
</script>