<?php Fisma_Format_Section::startSection('An Error Has Occurred&hellip;'); ?>
<?php
    if (Fisma::debug()) {
?>
    <p><i>Application is currently in debugging mode:</i></p>
    <p class="stacktrace"><?php echo $this->content; ?></p>
<?php    
    } else {
        echo $this->message;
    }
?>
<p>
    Technical Support Contact: <?php echo $this->contactName;?><br>
    Contact Phone: <?php echo $this->contactPhone;?><br>
    Contact E-mail: <a href="mailto:<?php echo $this->contactEmail;?>">
            <?php echo $this->contactEmail;?></a>
</p>

<?php Fisma_Format_Section::stopSection(); ?>
