<?php
echo $this->partial('network/searchbox.phtml', array('createNetworkPrivilege' => $this->createNetworkPrivilege));
$operation = '';
if ($this->updateNetworkObjPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteNetworkObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Network Information $operation"); ?>
<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
