
<?php /* the div for jqPlot to use (the JavaScript will create canvases in this */ ?>

<div class="yui-navset">

    <table width="100%" style="position: absolute; z-index: 1">
        <tr>
            <td align=right>
                <a href="JavaScript: // Click to show chart options";
                onClick="document.getElementById('<?php echo $this->escape($this->chartId, 'none'); ?>WidgetSpaceHolder').style.display='';">
                    <img src="/images/gear.png" width="35" />
                </a>
            </td>
        </tr>
    </table>

    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>loader" class="loading" style="width: 100%;">
        
        <div>
        </div>
        
    </div>
    
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>holder" <?php
                    echo $this->escape($this->divContainerArgs, 'none'); ?> >
    
            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>toplegend">
            </div>
            
            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>" >
                Loading chart data...
            </div>
    </div>

    <br/>
    <div id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpaceHolder" class="yui-navset" style="display: none; width: 400px; margin-left: auto; margin-right: auto;">
        <ul class="yui-nav">
            <li class="selected">
                <a href="#tab1">
                    <em>Chart Paramiters</em>
                </a>
            </li>
            <li>
                <a href="#tab1">
                    <em>Global Settings</em>
                </a>
            </li>
        </ul>            
        <div class="yui-content">
            <div id="tab1">
                <div id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpace">
                    <!-- char params and widgets placed here by JavaScript -->
                </div>
            </div>
            <div id="tab2" onClick="globalSettingUpdate('<?php echo $this->escape($this->chartId, 'none');?>');" style="text-align: left; ">
                <div id="<?php echo $this->escape($this->chartId, 'none');?>GlobSettings">
                <input type="checkbox" id="pointLabels" />
                    Draw point-labels (numbers on top of bars) <br/>
                <input type="checkbox" id="pointLabelsOutline" />
                    Outline point-labels <br/>
                <input type="checkbox" id="barShadows" />
                    Draw shadows behind bars <br/>
                <input type="textbox" id="barShadowDepth" value="3" style="width:10px" />
                    Depth of shadows behind bars (in pixels) <br/>                            
                <input type="checkbox" id="dropShadows" />
                    Draw shadows behind charts <br/>
                <input type="checkbox" id="gridLines"/>
                    Draw grid-lines <br/>
                <input type="checkbox" id="fadingDisabeled"/>
                    Disable fading effects <br/>
                </div>
            </div>
        </div>
    </div>    

    <script type="text/javascript">
        var thisName = <?php echo $this->escape($this->chartId, 'none');?>WidgetSpaceHolder;
        var tabView = new YAHOO.widget.TabView(thisName);
    </script> 
    
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>table" style="display:none">
    </div>   
    
</div>

<?php /* call javascript:createChartJQChart(obj) defined in jqplotWrapper.js which will create the chart */ ?>
<script>
    var thisChartObjData = <?php echo $this->escape($this->chartParamArr, 'json'); ?>;
    createJQChart(thisChartObjData);
</script>
