
<?php /* the div for jqPlot to use (the JavaScript will create canvases in this */ ?>

<div class="yui-navset">
    <div id="<?php 
        echo $this->escape($this->chartData['uniqueid'], 'none');
    ?>loader" class="loading" style="width:<?php
                        echo $this->escape($this->chartData['width'], 'none');
                    ?>px; height:<?php 
                        echo $this->escape($this->chartData['height'], 'none'); 
                    ?>px;">
        <div>
        </div>
    </div>
    <div id="<?php
                echo $this->escape($this->chartData['uniqueid'], 'none');
    ?>holder" <?php
                echo $this->escape($this->divContainerArgs, 'none');
    ?> >
                <div name="<?php
                        echo $this->escape($this->chartData['uniqueid'], 'none'); 
                    ?>" id="<?php
                        echo $this->escape($this->chartData['uniqueid'], 'none');
                    ?>" style="width:<?php
                                        echo $this->escape($this->chartData['width'], 'none');
                    ?>px; height:<?php 
                                        echo $this->escape($this->chartData['height'], 'none'); 
                    ?>px;">
                    Loading chart data...
                </div>
                <span id="<?php
                    echo $this->escape($this->chartData['uniqueid'], 'none');
                ?>WidgetSpace"></span>
    </div>
</div>

<?php /* call javascript:createChartJQChart(obj) defined in jqplotWrapper.js which will create the chart */ ?>
<script>
    var thisChartObjData = <?php echo $this->escape($this->chartData, 'json'); ?>;
    createJQChart(thisChartObjData);
</script>
