
<?php /* the div for jqPlot to use (the JavaScript will create canvases in this */ ?>

<div class="yui-navset">
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>loader" class="loading">
        
        <div>
        </div>
        
    </div>
    
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>holder" <?php
                    echo $this->escape($this->divContainerArgs, 'none'); ?> >
    
            <div id="<?php echo $this->escape($this->chartId, 'none'); ?>toplegend">
            </div>
            
                <div id="<?php echo $this->escape($this->chartId, 'none'); ?>" >
                    Loading chart data...
                </div>
                
                <span id="<?php echo $this->escape($this->chartId, 'none');?>WidgetSpace">
                </span>
    </div>
    
    <div id="<?php echo $this->escape($this->chartId, 'none'); ?>table" style="display:none">
    </div>
    
</div>

<?php /* call javascript:createChartJQChart(obj) defined in jqplotWrapper.js which will create the chart */ ?>
<script>
    var thisChartObjData = <?php echo $this->escape($this->chartParamArr, 'json'); ?>;
    createJQChart(thisChartObjData);
</script>
