<?php
echo $this->partial('asset/navibar.phtml', array('createAssetPrivilege' => $this->createAssetPrivilege));
$operation = '';
if ($this->updateAssetPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteAssetPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
Fisma_Format_Section::startSection("Asset $operation"); ?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
