<?php
echo $this->partial('user/searchbox.phtml', array('createUserPrivilege' => $this->createUserPrivilege));
$operation = '';
if ($this->updateUserObjPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}
if ($this->deleteUserObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}
if ($this->readUserObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->auditLogLink}'>Audit Log</a>]";
}
Fisma_Format_Section::startSection("User Account Information $operation"); ?>

<div>
    <?php echo $this->form; ?>
    <?php echo $this->tabView; ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
