<?php
echo $this->partial('source/searchbox.phtml', array('createSourcePrivilege' => $this->createSourcePrivilege));
$operation = '';

if ($this->updateSourceObjPrivilege) {
    $operation .= "[<a href='{$this->editLink}'>Edit</a>]";
}

if ($this->deleteSourceObjPrivilege) {
    $operation .= "&nbsp;&nbsp;[<a href='{$this->deleteLink}'>Delete</a>]";
}

Fisma_Format_Section::startSection("Finding Source Information $operation"); 
?>

<div>
    <?php echo $this->form ?>
</div>

<?php Fisma_Format_Section::stopSection(); ?>
