<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrComment extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_comment', array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 8), 'incidentid' => array('type' => 'integer', 'length' => 8), 'userid' => array('type' => 'integer', 'length' => 8), 'createdts' => array('type' => 'timestamp', 'length' => 25), 'comment' => array('type' => 'string', 'length' => 1000)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_comment');
    }
}