<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrHistory extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_history', array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 8), 'incidentid' => array('type' => 'integer', 'length' => 8), 'userid' => array('type' => 'integer', 'length' => 8), 'createdts' => array('type' => 'timestamp', 'length' => 25), 'type' => array('type' => 'enum', 'length' => 8, 'values' =>  array( 0 => 'COMMENT',  1 => 'WORKFLOW',  2 => 'REPORT',  3 => 'CLASSIFY',  4 => 'RESOLVE',  5 => 'CLOSE', )), 'name' => array('type' => 'string', 'length' => 255), 'description' => array('type' => 'string', 'length' => 1000)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_history');
    }
}