<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrAuditLog extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_audit_log', array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 8), 'incidentid' => array('type' => 'integer', 'length' => 8), 'createdts' => array('type' => 'timestamp', 'length' => 25), 'fieldname' => array('type' => 'string', 'length' => 255), 'origionalvalue' => array('type' => 'string', 'length' => 1000), 'newvalue' => array('type' => 'string', 'length' => 1000), 'userid' => array('type' => 'integer', 'length' => 8), 'addressip' => array('type' => 'string', 'length' => 15)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_audit_log');
    }
}