<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrIncidentWorkflow extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_incident_workflow', array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 8), 'incidentid' => array('type' => 'integer', 'length' => 8), 'roleid' => array('type' => 'integer', 'length' => 8), 'name' => array('type' => 'string', 'length' => 255), 'description' => array('type' => 'string', 'length' => 1000), 'cardinality' => array('type' => 'integer', 'length' => 8), 'status' => array('type' => 'enum', 'length' => 9, 'values' =>  array( 0 => 'queued',  1 => 'current',  2 => 'completed',  3 => 'reopened', )), 'completets' => array('type' => 'timestamp', 'length' => 25), 'comments' => array('type' => 'string', 'length' => 1000), 'attachment' => array('type' => 'string', 'length' => 255), 'userid' => array('type' => 'integer', 'length' => 8)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_incident_workflow');
    }
}