<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrIncidentActor extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_incident_actor', array('id' => array('type' => 'integer', 'length' => 8, 'autoincrement' => true, 'primary' => true), 'incidentid' => array('type' => 'integer', 'length' => 8), 'userid' => array('type' => 'integer', 'length' => 8)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_incident_actor');
    }
}