<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIrCategory extends Doctrine_Migration_Base
{
    public function up()
    {
		$this->createTable('ir_category', array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 8), 'createdts' => array('notnull' => true, 'type' => 'timestamp', 'length' => 25), 'modifiedts' => array('notnull' => true, 'type' => 'timestamp', 'length' => 25), 'name' => array('type' => 'string', 'length' => 255), 'description' => array('type' => 'string', 'extra' =>  array( 'purify' => 'html', ), 'length' => 1000), 'category' => array('type' => 'enum', 'length' => 4, 'values' =>  array( 0 => 'CAT0',  1 => 'CAT1',  2 => 'CAT2',  3 => 'CAT3',  4 => 'CAT4',  5 => 'CAT5',  6 => 'CAT6', )), 'deleted_at' => array('default' => NULL, 'notnull' => false, 'type' => 'timestamp', 'length' => 25)), array('indexes' => array(), 'primary' => array(0 => 'id')));
    }

    public function down()
    {
		$this->dropTable('ir_category');
    }
}