<?php
/**
 * Copyright (c) 2011 Endeavor Systems, Inc.
 *
 * This file is part of OpenFISMA.
 *
 * OpenFISMA is free software: you can redistribute it and/or modify it under the terms of the GNU General Public 
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * OpenFISMA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
 * details.
 *
 * You should have received a copy of the GNU General Public License along with OpenFISMA.  If not, see 
 * {@link http://www.gnu.org/licenses/}.
 */
/**
 * Change deletion behavior
 *
 * @package Migration
 * @copyright (c) Endeavor Systems, Inc. 2011 {@link http://www.endeavorsystems.com}
 * @author Dale Frey <dale.frey@endeavorsystems.com>
 * @license http://www.openfisma.org/content/license GPLv3
 */
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version106 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('asset', 'deleted_at');
        $this->removeColumn('network', 'deleted_at');
        $this->removeColumn('product', 'deleted_at');
        $this->removeColumn('role', 'deleted_at');
        $this->removeColumn('source', 'deleted_at');
    }

    public function down()
    {
        $this->addColumn(
            'asset', 'deleted_at', 'timestamp', '25',
            array(
                'default' => '',
                'notnull' => ''
            )
        );
        $this->addColumn(
            'network', 'deleted_at', 'timestamp', '25',
            array(
                'default' => '',
                'notnull' => ''
            )
        );
        $this->addColumn(
            'product', 'deleted_at', 'timestamp', '25',
            array(
                'default' => '',
                'notnull' => ''
            )
        );
        $this->addColumn(
            'role', 'deleted_at', 'timestamp', '25',
            array(
                'default' => '',
                'notnull' => ''
            )
        );
        $this->addColumn(
            'source', 'deleted_at', 'timestamp', '25',
            array(
                'default' => '',
                'notnull' => ''
            )
        );
    }
}