<?php
$uploadPanelButton = new Fisma_Yui_Form_Button('uploadPanelButton', 
                                               array('label' => 'Upload Document', 
                                                     'onClickFunction' => 'showUploadPanel'));
if (!$this->updateOrganizationObjPrivilege) {
    $uploadPanelButton->readOnly = true;
}
print $uploadPanelButton;

Fisma_Format_Section::startSection('System Documentation');
?>

<table border="1" class="systemDocuments">
    <tr>
        <th>File Name</th>
        <th>Size</th>
        <th>Version</th>
        <th>Version Notes</th>
        <th>Last Modified By User</th>
        <th>Last Modified Date</th>
        <th>View History</th>
    </tr>

<?php
foreach ($this->documents as $document) {
    print "<tr>"
        . "<td><a href='/system/download-document/id/{$document['id']}'>"
        . "<img src='{$document['iconUrl']}'>"
        . "<div>{$document['fileName']}</div></a></td>"
        . "<td>{$document['fileSize']}</td>"
        . "<td align='center'>{$document['version']}</td>"
        . "<td>{$document['description']}</td>"
        . "<td>{$document['username']}</td>"
        . "<td>{$document['updatedTs']}</td>"
        . "<td><a href='/panel/system-document/sub/view/id/{$document['id']}'>Version History</a></td>"
        . "</tr>";
}
?>

</table>

<?php
Fisma_Format_Section::stopSection();
?>
