<?php
Fisma_Format_Section::startSection('Details');
?>
<table class="keyValues">
    <tr>
        <td>System Name: </td>
        <td>
            <?php
            if ($this->updateOrganizationObjPrivilege) {
            ?>
            <span id="name" class="editable" target="name" name="name" type="text">
                <?php echo $this->organization['name']; ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->organization['name']; ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Nickname: </td>
        <td>
            <?php
            if ($this->updateOrganizationObjPrivilege) {
            ?>
            <span id="nickname" class="editable" target="nickname" name="nickname" type="text">
                <?php echo $this->organization['nickname']; ?>
            </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->organization['nickname']; ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>System Type: </td>
        <td>
            <?php
            if ($this->updateOrganizationObjPrivilege) {
            ?>
                <span id="type" 
                      class="editable" 
                      target="type" 
                      name="type" 
                      type="select" 
                      href="/metainfo/list/o/systemType/format/html/">
                    <?php echo $this->orgTypeLabel; ?>
                </span>
            <?php
            } else {
            ?>
            <span>
                <?php echo $this->orgTypeLabel; ?>
            </span>
            <?php
            }
            ?>
        </td>
    </tr>
    <tr>
        <td>Parent Organization: </td>
        <td>
            <?php
            $parentOrganization = $this->parentOrganization;
            if (isset($parentOrganization)):
                if ($this->readOrganizationObjPrivilege):
                    if ('system' == $parentOrganization['orgType']):
                        echo "<a href='/panel/system/sub/view/id/"
                             . $parentOrganization['id']
                             . "'>"
                             . $parentOrganization['nickname'] 
                             . "-"
                             . $parentOrganization['name']
                             . "</a>";
                    else:
                        echo "<a href='/panel/organization/sub/view/id/"
                             . $parentOrganization['id']
                             . "'>"
                             . $parentOrganization['nickname'] 
                             . "-"
                             . $parentOrganization['name']
                             . "</a>";
                    endif;
                else:
                    echo $parentOrganization['nickname'] . "-" . $parentOrganization['name'];
                endif;
            else:
                echo "<i>None</i>";
            endif;
            ?>
        </td>
    </tr>
</table>
<?php
Fisma_Format_Section::stopSection();

if ($this->updateOrganizationObjPrivilege) {
    Fisma_Format_Section::startSection('System Description', 'system_description');
} else {
    Fisma_Format_Section::startSection('System Description');
}
?>
<div name="description" id="system_description" type="textarea" rows="3" cols="120"> 
    <?php echo $this->safeHtml('organization.description'); ?>
</div>
<?php Fisma_Format_Section::stopSection(); ?>
